# Generated by Django 3.1.5 on 2025-04-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comment_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='post_id',
            field=models.IntegerField(null=True),
        ),
    ]
