# Generated by Django 3.1.5 on 2025-04-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_num_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='num_likes',
            field=models.IntegerField(default=0),
        ),
    ]
