# Generated by Django 3.1.5 on 2025-04-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20250419_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='post_followers', to='network.Comment'),
        ),
    ]
