# Generated by Django 3.1.5 on 2025-04-20 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20250419_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='post_follower', to='network.Follower'),
        ),
    ]
