# Generated by Django 3.1.5 on 2025-04-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20250419_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='follower_id',
        ),
        migrations.AddField(
            model_name='follower',
            name='userYouFollowId',
            field=models.IntegerField(default=0),
        ),
    ]
