# Generated by Django 3.1.5 on 2025-04-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20250419_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='follow',
        ),
        migrations.AddField(
            model_name='follower',
            name='follow',
            field=models.BooleanField(default=False),
        ),
    ]
