# Generated by Django 3.1.5 on 2025-04-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_auto_20250421_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='likeUnlike',
            field=models.BooleanField(default=False),
        ),
    ]
