# Generated by Django 3.1.5 on 2022-01-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20220105_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=128)),
                ('starting_bid', models.IntegerField()),
                ('category', models.CharField(max_length=21)),
                ('URL_image', models.URLField(blank=True)),
            ],
        ),
    ]
