# Generated by Django 3.1.5 on 2022-01-17 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_new_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='flights',
        ),
        migrations.DeleteModel(
            name='Bids',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Listings',
        ),
    ]
