# Generated by Django 3.1.5 on 2022-02-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20220116_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userwatchlist', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('starting_bid', models.IntegerField()),
                ('URL_image', models.URLField(blank=True)),
            ],
        ),
    ]
