# Generated by Django 3.1.5 on 2022-02-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_add_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Coments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment', models.CharField(max_length=128)),
                ('usercoment', models.IntegerField()),
            ],
        ),
    ]
