# Generated by Django 3.1.5 on 2022-02-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_new_coments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='len_watchlist',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='userwatchlist',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
