# Generated by Django 3.1.5 on 2022-02-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20220213_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('userbid', models.IntegerField()),
            ],
        ),
    ]
