# Generated by Django 3.1.5 on 2022-02-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_new_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_bid',
            name='userbid',
        ),
        migrations.AddField(
            model_name='new_bid',
            name='Listings_id',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='new_bid',
            name='bid',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
