# Generated by Django 3.1.5 on 2022-02-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20220213_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_watchlist',
            name='starting_bid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='add_watchlist',
            name='userwatchlist',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='new_bid',
            name='Listings_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='new_bid',
            name='bid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='new_coments',
            name='usercoment',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='new_listings',
            name='starting_bid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='len_watchlist',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userwatchlist',
            field=models.IntegerField(null=True),
        ),
    ]
