# Generated by Django 3.1.5 on 2022-02-15 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20220214_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='len_watchlist',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userwatchlist',
        ),
        migrations.AddField(
            model_name='new_listings',
            name='user_L',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
