# Generated by Django 3.1.5 on 2022-02-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20220215_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='len_watchlist',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='userwatchlist',
            field=models.IntegerField(null=True),
        ),
    ]
