# Generated by Django 3.1.5 on 2022-02-15 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20220215_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_listings',
            old_name='user_L',
            new_name='user',
        ),
        migrations.AddField(
            model_name='add_watchlist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
