# Generated by Django 3.1.5 on 2022-02-15 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20220215_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_bid',
            name='userbid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_userbid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='new_coments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_Coments', to=settings.AUTH_USER_MODEL),
        ),
    ]
