# Generated by Django 3.1.5 on 2022-02-18 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_new_bid_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_bid',
            name='starting_bid',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='star_bid', to='auctions.new_listings'),
        ),
    ]
