# Generated by Django 3.1.5 on 2022-02-18 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20220218_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_bid',
            name='starting_bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='star_bid', to='auctions.new_listings'),
        ),
    ]
