# Generated by Django 3.1.5 on 2022-02-20 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20220218_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='close_action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Close_Listings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CloseListing', to='auctions.new_listings')),
                ('Winner_bid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CloseListing', to='auctions.new_bid')),
            ],
        ),
    ]
