# Generated by Django 3.1.5 on 2022-02-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_close_action'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='close_action',
            new_name='close_listing_action',
        ),
    ]
