# Generated by Django 3.1.5 on 2022-02-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20220220_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='close_listing_action',
            name='Close_Listings',
        ),
        migrations.RemoveField(
            model_name='close_listing_action',
            name='Winner_bid',
        ),
        migrations.AddField(
            model_name='close_listing_action',
            name='Listings_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='close_listing_action',
            name='URL_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='close_listing_action',
            name='bid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='close_listing_action',
            name='category',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='close_listing_action',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='close_listing_action',
            name='starting_bid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='close_listing_action',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='close_listing_action',
            name='user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
