# Generated by Django 3.1.5 on 2022-02-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20220220_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='close_listing_action',
            name='userbid',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
